## Importing Libraries and Dependencies

In [19]:
#Importing the Libraries
import numpy as np
import pandas as pd
import datetime
import matplotlib
import matplotlib.pyplot as plt
from matplotlib import colors
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
#from yellowbrick.cluster import KElbowVisualizer
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt, numpy as np
from mpl_toolkits.mplot3d import Axes3D
from sklearn.cluster import AgglomerativeClustering
from matplotlib.colors import ListedColormap
from sklearn import metrics
import warnings
import sys
if not sys.warnoptions:
    warnings.simplefilter("ignore")
pd.set_option('display.max_columns', None)

In [20]:
customer_data = pd.read_csv('SupplyChainData.csv')

In [21]:
customer_data.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Cally,20755,Holloway,XXXXXXXXX,Consumer,PR,5365 Noble Nectar Island,725.0,2,Fitness,18.251453,-66.037056,Pacific Asia,Bekasi,Indonesia,20755,1/31/2018 22:56,77202,1360,13.110000,0.04,180517,327.75,0.29,1,327.75,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,02/03/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Irene,19492,Luna,XXXXXXXXX,Consumer,PR,2679 Rustic Loop,725.0,2,Fitness,18.279451,-66.037064,Pacific Asia,Bikaner,India,19492,1/13/2018 12:27,75939,1360,16.389999,0.05,179254,327.75,-0.80,1,327.75,311.359985,-249.089996,South Asia,Rajast√°n,PENDING,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,XXXXXXXXX,Gillian,19491,Maldonado,XXXXXXXXX,Consumer,CA,8510 Round Bear Gate,95125.0,2,Fitness,37.292233,-121.881279,Pacific Asia,Bikaner,India,19491,1/13/2018 12:06,75938,1360,18.030001,0.06,179253,327.75,-0.80,1,327.75,309.720001,-247.779999,South Asia,Rajast√°n,CLOSED,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,XXXXXXXXX,Tana,19490,Tate,XXXXXXXXX,Home Office,CA,3200 Amber Bend,90027.0,2,Fitness,34.125946,-118.291016,Pacific Asia,Townsville,Australia,19490,1/13/2018 11:45,75937,1360,22.940001,0.07,179252,327.75,0.08,1,327.75,304.809998,22.860001,Oceania,Queensland,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Orli,19489,Hendricks,XXXXXXXXX,Corporate,PR,8671 Iron Anchor Corners,725.0,2,Fitness,18.253769,-66.037048,Pacific Asia,Townsville,Australia,19489,1/13/2018 11:24,75936,1360,29.500000,0.09,179251,327.75,0.45,1,327.75,298.250000,134.210007,Oceania,Queensland,PENDING_PAYMENT,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [22]:
customer_data.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,Longitude,Order Customer Id,Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,-84.915675,6691.379495,36221.894903,692.509764,20.664741,0.101668,90260.000000,141.232550,0.120647,2.127638,203.772096,183.107609,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,21.433241,4162.918106,21045.379569,336.446807,21.800901,0.070415,52111.490959,139.732492,0.466796,1.453451,132.273077,120.043670,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,-158.025986,1.000000,1.000000,19.000000,0.000000,0.000000,1.000000,9.990000,-2.750000,1.000000,9.990000,7.490000,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,-98.446312,3258.500000,18057.000000,403.000000,5.400000,0.040000,45130.500000,50.000000,0.080000,1.000000,119.980003,104.379997,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,-76.847908,6457.000000,36140.000000,627.000000,14.000000,0.100000,90260.000000,59.990002,0.270000,1.000000,199.919998,163.990005,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,-66.370583,9779.000000,54144.000000,1004.000000,29.990000,0.160000,135389.500000,199.990005,0.360000,3.000000,299.950012,247.399994,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,115.263077,20757.000000,77204.000000,1363.000000,500.000000,0.250000,180519.000000,1999.989990,0.500000,5.000000,1999.989990,1939.989990,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0

In [23]:
customer_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Days for shipping (real),180519.0,3.497654,1.623722,0.000000,2.000000,3.000000,5.000000,6.000000
Days for shipment (scheduled),180519.0,2.931847,1.374449,0.000000,2.000000,4.000000,4.000000,4.000000
Benefit per order,180519.0,21.974989,104.433526,-4274.979980,7.000000,31.520000,64.800003,911.799988
Sales per customer,180519.0,183.107609,120.043670,7.490000,104.379997,163.990005,247.399994,1939.989990
Late_delivery_risk,180519.0,0.548291,0.497664,0.000000,0.000000,1.000000,1.000000,1.000000
Category Id,180519.0,31.851451,15.640064,2.000000,18.000000,29.000000,45.000000,76.000000
Customer Id,180519.0,6691.379495,4162.918106,1.000000,3258.500000,6457.000000,9779.000000,20757.000000
Customer Zipcode,180516.0,35921.126914,37542.461122,603.000000,725.000000,19380.000000,78207.000000,99205.000000
Department Id,180519.0,5.443460,1.629246,2.000000,4.000000,5.000000,7.000000,12.000000
Latitude,180519.0,29.719955,9.813646,-33.937553,18.265432,33.144863,39.279617,48.781933
Longitude,180519.0,-84.915675,21.433241,-158.025986,-98.446312,-76.847908,-66.370583,115.263077
Order Customer Id,180519.0,6691.379495,4162.918106,1.000000,3258.500000,6457.000000,9779.000000,20757.000000
Order Id,180519.0,36221.894903,21045.379569,1.000000,18057.000000,36140.000000,54144.000000,77204.000000
Order Item Cardprod Id,180519.0,692.509764,336.446807,19.000000,403.000000,627.000000,1004.000000,1363.000000
Order Item Discount,180519.0,20.664741,21.800901,0.000000,5.400000,14.000000,29.990000,500.000000
Order Item Discount Rate,180519.0,0.101668,0.070415,0.000000,0.040000,0.100000,0.160000,0.250000
Order Item Id,180519.0,90260.000000,52111.490959,1.000000,45130.500000,90260.000000,135389.500000,180519.000000
Order Item Product Price,180519.0,141.232550,139.732492,9.990000,50.000000,59.990002,199.990005,1999.989990
Order Item Profit Ratio,180519.0,0.120647,0.466796,-2.750000,0.080000,0.270000,0.360000,0.500000
Order Item Quantity,180519.0,2.127638,1.453451,1.000000,1.000000,1.000000,3.000000,5.000000
Sales,180519.0,203.772096,132.273077,9.990000,119.980003,199.919998,299.950012,1999.989990
Order Item Total,180519.0,183.107609,120.043670,7.490000,104.379997,163.990005,247.399994,1939.989990
Order Profit Per Order,180519.0,21.974989,104.433526,-4274.979980,7.000000,31.520000,64.800003,911.799988
Order Zipcode,24840.0,55426.132327,31919.279101,1040.000000,23464.000000,59405.000000,90008.000000,99301.000000
Product Card Id,180519.0,692.509764,336.446807,19.000000,403.000000,627.000000,1004.000000,1363.000000
Product Category Id,180519.0,31.851451,15.640064,2.000000,18.000000,29.000000,45.000000,76.000000
Product Description,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product Price,180519.0,141.232550,139.732492,9.990000,50.000000,59.990002,199.990005,1999.989990
Product Status,180519.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [24]:
customer_data.shape

(180519, 53)

In [25]:
customer_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [26]:
customer_data1 = customer_data[['Market', 'Customer Id']].drop_duplicates()

In [27]:
customer_data1.groupby(['Market'])['Customer Id'].aggregate('count').reset_index().sort_values('Customer Id', ascending = False)

         Market  Customer Id
3  Pacific Asia        13267
1        Europe        11657
2         LATAM         9325
4          USCA         6256
0        Africa         3311

In [28]:
# Filter and keep ddata from Latin America

customer_data1 = customer_data1.query("Market == 'LATAM'").reset_index(drop=True)

In [29]:
#Check for missing values in the dataset

customer_data.isnull().sum(axis=0)

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

In [34]:
#check for the minimum
customer_data1.Sales.min()

AttributeError: 'DataFrame' object has no attribute 'Sales'

In [36]:
customer_data1 = customer_data1.loc[customer_data1['Order Item Quantity']>0]

KeyError: 'Order Item Quantity'

In [27]:
customer_data.sort_values(by='Sales', inplace=True, ascending = False)

In [31]:
customer_data.head(10)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
82161,DEBIT,5,4,721.599976,1639.98999,Late delivery,1,10,Strength Training,Augusta,EE. UU.,XXXXXXXXX,Mary,1148,Anderson,XXXXXXXXX,Consumer,GA,7213 Cozy Quay,30907.0,3,Footwear,33.521042,-82.049355,Europe,Marseille,Francia,1148,9/30/2017 4:43,68724,208,360.0,0.18,171811,1999.98999,0.44,1,1999.98999,1639.98999,721.599976,Western Europe,Provenza-Alpes-Costa Azul,COMPLETE,NaN,208,10,NaN,http://images.acmesports.sports/SOLE+E35+Ellip...,SOLE E35 Elliptical,1999.98999,0,10/05/2017 04:43,Standard Class
48281,DEBIT,2,2,864.000000,1799.98999,Shipping on time,0,10,Strength Training,Amarillo,EE. UU.,XXXXXXXXX,Phillip,2564,Smith,XXXXXXXXX,Corporate,TX,6068 Quaking Heath,79109.0,3,Footwear,35.187542,-101.867622,Europe,Draguignan,Francia,2564,10/01/2017 14:42,68821,208,200.0,0.10,172060,1999.98999,0.48,1,1999.98999,1799.98999,864.000000,Western Europe,Provenza-Alpes-Costa Azul,COMPLETE,NaN,208,10,NaN,http://images.acmesports.sports/SOLE+E35+Ellip...,SOLE E35 Elliptical,1999.98999,0,10/03/2017 14:42,Second Class
141117,DEBIT,2,1,187.580002,1659.98999,Late delivery,1,10,Strength Training,Caguas,Puerto Rico,XXXXXXXXX,Helen,8462,Smith,XXXXXXXXX,Home Office,PR,1577 Green Vista,725.0,3,Footwear,18.251719,-66.370613,Europe,Plymouth,Reino Unido,8462,9/30/2017 8:55,68736,208,340.0,0.17,171837,1999.98999,0.11,1,1999.98999,1659.98999,187.580002,Northern Europe,Inglaterra,COMPLETE,NaN,208,10,NaN,http://images.acmesports.sports/SOLE+E35+Ellip...,SOLE E35 Elliptical,1999.98999,0,10/02/2017 08:55,First Class
83214,DEBIT,6,4,264.959992,1919.98999,Late delivery,1,10,Strength Training,Seattle,EE. UU.,XXXXXXXXX,Matthew,10637,Smith,XXXXXXXXX,Consumer,WA,851 Blue Elk Walk,98115.0,3,Footwear,47.678699,-122.321762,Europe,Rennes,Francia,10637,10/02/2017 09:37,68875,208,80.0,0.04,172181,1999.98999,0.14,1,1999.98999,1919.98999,264.959992,Western Europe,Breta√±a,ON_HOLD,NaN,208,10,NaN,http://images.acmesports.sports/SOLE+E35+Ellip...,SOLE E35 Elliptical,1999.98999,0,10/08/2017 09:37,Standard Class
12606,DEBIT,4,4,45.000000,1499.98999,Shipping on time,0,10,Strength Training,Caguas,Puerto Rico,XXXXXXXXX,Victoria,9515,Smith,XXXXXXXXX,Consumer,PR,870 High View Close,725.0,3,Footwear,18.252848,-66.370529,Europe,Colchester,Reino Unido,9515,9/29/2017 21:22,68703,208,500.0,0.25,171765,1999.98999,0.03,1,1999.98999,1499.98999,45.000000,Northern Europe,Inglaterra,COMPLETE,NaN,208,10,NaN,http://images.acmesports.sports/SOLE+E35+Ellip...,SOLE E35 Elliptical,1999.98999,0,10/03/2017 21:22,Standard Class
159182,TRANSFER,2,4,-952.559998,1679.98999,Advance shipping,0,10,Strength Training,Caguas,Puerto Rico,XXXXXXXXX,Mary,382,Lane,XXXXXXXXX,Consumer,PR,7666 High Dale Bank,725.0,3,Footwear,18.247520,-66.025269,Europe,Le Havre,Francia,382,9/30/2017 19:26,68766,208,320.0,0.16,171920,1999.98999,-0.57,1,1999.98999,1679.98999,-952.559998,Western Europe,Normand√≠a,PROCESSING,NaN,208,10,NaN,http://images.acmesports.sports/SOLE+E35+Ellip...,SOLE E35 Elliptical,1999.98999,0,10/02/2017 19:26,Standard Class
82117,DEBIT,4,4,686.070007,1889.98999,Shipping on time,0,10,Strength Training,Palatine,EE. UU.,XXXXXXXXX,Samantha,10744,Smith,XXXXXXXXX,Consumer,IL,5129 Indian Maze,60067.0,3,Footwear,42.111866,-88.048714,Europe,Sant Boi de Llobregat,Espa√±a,10744,10/02/2017 03:40,68858,208,110.0,0.06,172140,1999.98999,0.36,1,1999.98999,1889.98999,686.070007,Southern Europe,Catalu√±a,COMPLETE,NaN,208,10,NaN,http://images.acmesports.sports/SOLE+E35+Ellip...,SOLE E35 Elliptical,1999.98999,0,10/06/2017 03:40,Standard Class
82130,DEBIT,3,4,473.200012,1819.98999,Advance shipping,0,10,Strength Training,Bronx,EE. UU.,XXXXXXXXX,Richard,1223,Perry,XXXXXXXXX,Consumer,NY,1655 Little Bear Circle,10469.0,3,Footwear,40.838802,-73.870995,Europe,Rostock,Alemania,1223,10/01/2017 20:19,68837,208,180.0,0.09,172101,1999.98999,0.26,1,1999.98999,1819.98999,473.200012,Western Europe,Mecklemburgo-Pomerania Occidental,COMPLETE,NaN,208,10,NaN,http://images.acmesports.sports/SOLE+E35+Ellip...,SOLE E35 Elliptical,1999.98999,0,10/04/2017 20:19,Standard Class
13343,DEBIT,5,4,660.000000,1759.98999,Late delivery,1,10,Strength Training,Caguas,Puerto Rico,XXXXXXXXX,Daniel,5946,Smith,XXXXXXXXX,Consumer,PR,4823 Golden Hollow,725.0,3,Footwear,18.237732,-66.370621,Europe,Genoa,Italia,5946,10/01/2017 10:30,68809,208,240.0,0.12,172032,1999.98999,0.38,1,1999.98999,1759.98999,660.000000,Southern Europe,Liguria,ON_HOLD,NaN,208,10,NaN,http://images.acmesports.sports/SOLE+E35+Ellip...,SOLE E35 Elliptical,1999.98999,0,10/06/2017 10:30,Standard Class
148406,DEBIT,4,4,-1246.089966,1699.98999,Shipping on time,0,10,Strength Training,Caguas,Puerto Rico,XXXXXXXXX,Catherine,986,Hawkins,XXXXXXXXX,Home Office,PR,3651 Rustic Cape,725.0,3,Footwear,18.227577,-66.044533,Europe,Milan,Italia,986,9/30/2017 23:38,68778,208,300.0,0.15,171961,1999.98999,-0.73,1,1999.98999,1699.98999,-1246.089966,Southern Europe,Lombard√≠a,COMPLETE,NaN,208,10,NaN,http://images.acmesports.sports/SOLE+E35+Ellip...,SOLE E35 Elliptical,1999.98999,0,10/04/2017 23:38,Standard Class

In [33]:
customer_data['Product Description'].fillna(36, inplace=True)

In [34]:
customer_data.head(10)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
82161,DEBIT,5,4,721.599976,1639.98999,Late delivery,1,10,Strength Training,Augusta,EE. UU.,XXXXXXXXX,Mary,1148,Anderson,XXXXXXXXX,Consumer,GA,7213 Cozy Quay,30907.0,3,Footwear,33.521042,-82.049355,Europe,Marseille,Francia,1148,9/30/2017 4:43,68724,208,360.0,0.18,171811,1999.98999,0.44,1,1999.98999,1639.98999,721.599976,Western Europe,Provenza-Alpes-Costa Azul,COMPLETE,NaN,208,10,36.0,http://images.acmesports.sports/SOLE+E35+Ellip...,SOLE E35 Elliptical,1999.98999,0,10/05/2017 04:43,Standard Class
48281,DEBIT,2,2,864.000000,1799.98999,Shipping on time,0,10,Strength Training,Amarillo,EE. UU.,XXXXXXXXX,Phillip,2564,Smith,XXXXXXXXX,Corporate,TX,6068 Quaking Heath,79109.0,3,Footwear,35.187542,-101.867622,Europe,Draguignan,Francia,2564,10/01/2017 14:42,68821,208,200.0,0.10,172060,1999.98999,0.48,1,1999.98999,1799.98999,864.000000,Western Europe,Provenza-Alpes-Costa Azul,COMPLETE,NaN,208,10,36.0,http://images.acmesports.sports/SOLE+E35+Ellip...,SOLE E35 Elliptical,1999.98999,0,10/03/2017 14:42,Second Class
141117,DEBIT,2,1,187.580002,1659.98999,Late delivery,1,10,Strength Training,Caguas,Puerto Rico,XXXXXXXXX,Helen,8462,Smith,XXXXXXXXX,Home Office,PR,1577 Green Vista,725.0,3,Footwear,18.251719,-66.370613,Europe,Plymouth,Reino Unido,8462,9/30/2017 8:55,68736,208,340.0,0.17,171837,1999.98999,0.11,1,1999.98999,1659.98999,187.580002,Northern Europe,Inglaterra,COMPLETE,NaN,208,10,36.0,http://images.acmesports.sports/SOLE+E35+Ellip...,SOLE E35 Elliptical,1999.98999,0,10/02/2017 08:55,First Class
83214,DEBIT,6,4,264.959992,1919.98999,Late delivery,1,10,Strength Training,Seattle,EE. UU.,XXXXXXXXX,Matthew,10637,Smith,XXXXXXXXX,Consumer,WA,851 Blue Elk Walk,98115.0,3,Footwear,47.678699,-122.321762,Europe,Rennes,Francia,10637,10/02/2017 09:37,68875,208,80.0,0.04,172181,1999.98999,0.14,1,1999.98999,1919.98999,264.959992,Western Europe,Breta√±a,ON_HOLD,NaN,208,10,36.0,http://images.acmesports.sports/SOLE+E35+Ellip...,SOLE E35 Elliptical,1999.98999,0,10/08/2017 09:37,Standard Class
12606,DEBIT,4,4,45.000000,1499.98999,Shipping on time,0,10,Strength Training,Caguas,Puerto Rico,XXXXXXXXX,Victoria,9515,Smith,XXXXXXXXX,Consumer,PR,870 High View Close,725.0,3,Footwear,18.252848,-66.370529,Europe,Colchester,Reino Unido,9515,9/29/2017 21:22,68703,208,500.0,0.25,171765,1999.98999,0.03,1,1999.98999,1499.98999,45.000000,Northern Europe,Inglaterra,COMPLETE,NaN,208,10,36.0,http://images.acmesports.sports/SOLE+E35+Ellip...,SOLE E35 Elliptical,1999.98999,0,10/03/2017 21:22,Standard Class
159182,TRANSFER,2,4,-952.559998,1679.98999,Advance shipping,0,10,Strength Training,Caguas,Puerto Rico,XXXXXXXXX,Mary,382,Lane,XXXXXXXXX,Consumer,PR,7666 High Dale Bank,725.0,3,Footwear,18.247520,-66.025269,Europe,Le Havre,Francia,382,9/30/2017 19:26,68766,208,320.0,0.16,171920,1999.98999,-0.57,1,1999.98999,1679.98999,-952.559998,Western Europe,Normand√≠a,PROCESSING,NaN,208,10,36.0,http://images.acmesports.sports/SOLE+E35+Ellip...,SOLE E35 Elliptical,1999.98999,0,10/02/2017 19:26,Standard Class
82117,DEBIT,4,4,686.070007,1889.98999,Shipping on time,0,10,Strength Training,Palatine,EE. UU.,XXXXXXXXX,Samantha,10744,Smith,XXXXXXXXX,Consumer,IL,5129 Indian Maze,60067.0,3,Footwear,42.111866,-88.048714,Europe,Sant Boi de Llobregat,Espa√±a,10744,10/02/2017 03:40,68858,208,110.0,0.06,172140,1999.98999,0.36,1,1999.98999,1889.98999,686.070007,Southern Europe,Catalu√±a,COMPLETE,NaN,208,10,36.0,http://images.acmesports.sports/SOLE+E35+Ellip...,SOLE E35 Elliptical,1999.98999,0,10/06/2017 03:40,Standard Class
82130,DEBIT,3,4,473.200012,1819.98999,Advance shipping,0,10,Strength Training,Bronx,EE. UU.,XXXXXXXXX,Richard,1223,Perry,XXXXXXXXX,Consumer,NY,1655 Little Bear Circle,10469.0,3,Footwear,40.838802,-73.870995,Europe,Rostock,Alemania,1223,10/01/2017 20:19,68837,208,180.0,0.09,172101,1999.98999,0.26,1,1999.98999,1819.98999,473.200012,Western Europe,Mecklemburgo-Pomerania Occidental,COMPLETE,NaN,208,10,36.0,http://images.acmesports.sports/SOLE+E35+Ellip...,SOLE E35 Elliptical,1999.98999,0,10/04/2017 20:19,Standard Class
13343,DEBIT,5,4,660.000000,1759.98999,Late delivery,1,10,Strength Training,Caguas,Puerto Rico,XXXXXXXXX,Daniel,5946,Smith,XXXXXXXXX,Consumer,PR,4823 Golden Hollow,725.0,3,Footwear,18.237732,-66.370621,Europe,Genoa,Italia,5946,10/01/2017 10:30,68809,208,240.0,0.12,172032,1999.98999,0.38,1,1999.98999,1759.98999,660.000000,Southern Europe,Liguria,ON_HOLD,NaN,208,10,36.0,http://images.acmesports.sports/SOLE+E35+Ellip...,SOLE E35 Elliptical,1999.98999,0,10/06/2017 10:30,Standard Class
148406,DEBIT,4,4,-1246.089966,1699.98999,Shipping on time,0,10,Strength Training,Caguas,Puerto Rico,XXXXXXXXX,Catherine,986,Hawkins,XXXXXXXXX,Home Office,PR,3651 Rustic Cape,725.0,3,Footwear,18.227577,-66.044533,Europe,Milan,Italia,986,9/30/2017 23:38,68778,208,300.0,0.15,171961,1999.98999,-0.73,1,1999.98999,1699.98999,-1246.089966,Southern Europe,Lombard√≠a,COMPLETE,NaN,208,10,36.0,http://images.acmesports.sports/SOLE+E35+Ellip...,SOLE E35 Elliptical,1999.98999,0,10/04/2017 23:38,Standard Class